### PR TITLE
Annotation processor for Swagger annotations.

### PR DESCRIPTION
**Pull request by pilhuhn**
This processor generates adoc and xml output from the Swagger + Jax-RS annotations

While writing it, I move the other maven package one level deeper

### CODE REVIEW

**Comment by ppalaga** [comment]
The annotation processor code seems to be pretty generic. Is there any upstream where this could be contributed? I am OK with putting it here for short or long time, I just want to adapt my expectations :)

**Comment by pilhuhn** [comment]
In theory it could be added to Swagger - but last time I tried that, there was no interest

**Comment by ppalaga** [comment]
I vote for making the java package name shorter and more meaningfull:
`org.hawkular.helpers.rest_docs_generator` -> `org.hawkular.annotation.restdoc`

**Comment by pilhuhn** [comment]
Well, this is not an annotation package, but a annotation processor. But +1 for shorter name  `org.hawkular.apt.restdoc`?

**Comment by ppalaga** [comment]
Merged, thanks!

**Pull request merged**
