### PR TITLE
Idea import order

### PR DESCRIPTION
**Pull request by jkremser**
This PR expands the settings.jar into readable/editable set of config files to be able to keep track of the changes in git.

If you need the `settings.jar`, just run `mvn install` and you should find it in the target directory.

The second part fixes the issue with import order in idea. Organize imports now should work as expected

**EDIT:**
There is a commit that forces each java construct to wrap if it is longer than 120 
         chars. Also it indents the same logical constructs on top of
         each other, example:

``` java
         myAwesomeBuilder.verrrryyyyLoooonnnnggggFoooooooooo1()
                         .verrrryyyyLoooonnnnggggFoooooooooo2()
                         .verrrryyyyLoooonnnnggggFoooooooooo3()
```

 or during the method call:

``` java
         myAwesomeMethod(verrrryyyyLoooonnnnggggFooooooooo1,
                         verrrryyyyLoooonnnnggggFooooooooo2,
                         verrrryyyyLoooonnnnggggFooooooooo3)
```

On the other hand, there are some corner cases where the
combination of the rules produces kind of strange looking lines
like:

``` java
         assertEquals("bla", 0, personaService.getEffectiveRolesForResource(user,
                                                                            resource)
                                              .size());
```

I.e. the method parameters are under each other and the chained method calls as well. I found this more readable, even though strange looking at the first sight.

All in all, it passes the checkstyle and we can improve on it.

**EDIT2:**
Alligning the same logical constructs on top of each other (the ^) doesn't work with long strings, so I am commenting out this feature, until we figure out how to fix it.

### CODE REVIEW

**Comment by ppalaga** [comment]
@Jiri-Kremser thanks! @jpkroehling kindly declared himself to be ready to test both #21 and #22 with IntelliJ.

**Comment by jpkrohling** [comment]
Looks good to me.

**Comment by jpkrohling** [comment]
Looks good to me! I had some troubles in re-importing the settings.jar , but importing, then restarting IntelliJ, then importing again made it work

**Comment by jpkrohling** [comment]
Last comment: the organize imports is fixed. There's still an issue with the "source formatting", but it's not on the scope of this issue.

**Comment by ppalaga** [comment]
Thank you guys!

**Comment by jkremser** [comment]
> Looks good to me! I had some troubles in re-importing the settings.jar , but importing, then restarting IntelliJ, then importing again made it work

I had the same issue, what helps is removing the settings. I've described it here: http://git.io/vO1E4

> Last comment: the organize imports is fixed. There's still an issue with the "source formatting", but it's not on the scope of this issue.

Thanks for the merge, I'll rather keep track of the possible issues discussed on IRC:

```
<jpkroehling> jkremser, now it seems it fails on pom.xml :D
<jpkroehling> sorry, not on pom.xml
<jpkroehling> /mnt/storage/projects/hawkular-accounts/.travis.maven.settings.xml
<jpkroehling> /mnt/storage/projects/hawkular-accounts/.travis.maven.settings.xml:24:22: Expected indent 2 before start element <interactiveMode>
...
/mnt/storage/projects/hawkular-accounts/jaxb-adapters/src/test/java/org/hawkular/accounts/jaxb/adapters/ZonedDateTimeXmlAdapterTest.java:21: Wrong order for 'java.time.ZoneId' import.
<jpkroehling> /mnt/storage/projects/hawkular-accounts/jaxb-adapters/src/main/java/org/hawkular/accounts/jaxb/adapters/ZonedDateTimeXmlAdapter.java:20: Wrong order for 'java.time.ZoneOffset' import.
<jpkroehling> with only Organize Imports
```

I'll try to reproduce and then create a new PR for it.

**Pull request merged**
