### PR TITLE
Add readme file for setting up preferences for Eclipse

### PR DESCRIPTION
**Pull request by Akki5**

### CODE REVIEW

**Comment by pilhuhn** [comment]
Thank you for your PR "unfortunately" we have decided that documentation has to be written in AsciiDoc(tor), `*.adoc`.  Can you please convert the readme? We also need to add that to the developers guide on hawkular.org

You can find an AsciiDoctor user manual here: http://asciidoctor.org/docs/user-manual/

**Comment by Akki5** [comment]
Yeah, okay. Thanks for the reply. I will try to do it asap.

**Comment by Akki5** [comment]
Hey Pilhuhn, I have tried to convert .md file into .adoc file. Please see to it once, I think it should work correctly.

**Comment by pilhuhn** [comment]
lgtm - @jmazzitelli can you as Eclipse user check this?

**Comment by pilhuhn** [comment]
Thanks Mazz

**Pull request merged**
