### PR TITLE
Emit information about the inheritance of the data types.

### PR DESCRIPTION
**Pull request by metlos**

### CODE REVIEW

**Comment by metlos** [comment]
@pavolloffay could you please take a look at this?

**Comment by pavolloffay** [comment]
LGTM, but author of the script is @tsegismont could you please look at this too?

**Comment by metlos** [comment]
Don't merge this yet, pls. I will need to add some additional logic for the case of inheritance AND some new properties.

**Comment by metlos** [comment]
@tsegismont would you please review? I think this is good to go.

**Comment by objectiser** [comment]
@metlos Script looks good - only issue I had was with one data type in APM (InteractionNode) that had two fields of type Message - the swagger.json had the correct reference, but the generated adoc had 'null' types for both fields. I've emailed the two files to the hawk-dev ml.

**Comment by metlos** [comment]
@objectiser, your case should be handled now, too. Nice find...

**Comment by objectiser** [comment]
:+1:  works great

**Comment by metlos** [comment]
@pilhuhn, who has the commit access to this repo? I'd like to merge this and release new build tools asap...

**Pull request merged**
